# Generated by Django 5.0.6 on 2024-07-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='collectios',
            new_name='collection',
        ),
    ]
