# Generated by Django 5.0.6 on 2024-07-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_collectios_comment_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='myapp.collections'),
        ),
    ]
